### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by xokko** [NathanWalker/nativescript-spotify#1]
I tried to run the demo on android but it failed. The important message is this:

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.spotify.sdk.android.authentication.AuthenticationResponse$QueryParams conflict: D:\dev\nativescript-spotify-master\demo\platforms\android\build\intermediates\exploded-aar\spotify-auth-1.0.0-beta12\jars\classes.jar and D:\dev\nativescript-spotify-master\demo\platforms\android\build\intermediates\exploded-aar\com.spotify.sdk\spotify-auth\1.0.0-beta12\jars\classes.jar
        at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.
```

There are two directories with the SDK `..\exploded-aar\spotify-auth-1.0.0-beta12` and  `..exploded-aar\com.spotify.sdk\spotify-auth\1.0.0-beta12\`
Also spotify-player is in these two places.
Is there a fix for this?

**Comment by NathanWalker** [comment]
It's iOS only at the moment. Hopefully Android support will come over the next 2 weeks.

**Comment by xokko** [comment]
This explains everything... Thanks!
